In [36]:
import numpy as np
import glob
import csv
from tqdm import tqdm
from conditional import conditional
from os.path import join
import pandas as pd
from sklearn.utils.extmath import softmax
CLASSES = [
    'HTC-1-M7',
    'iPhone-6',     
    'Motorola-Droid-Maxx',
    'Motorola-X',
    'Samsung-Galaxy-S4',
    'iPhone-4s',
    'LG-Nexus-5x', 
    'Motorola-Nexus-6',
    'Samsung-Galaxy-Note3',
    'Sony-NEX-7']
TEST_FOLDER = '../input/test/'
pd.set_option('display.height', 10000)
pd.set_option('display.max_rows', 5000)
pd.set_option('display.max_columns', 5000)
pd.set_option('display.width', 10000)

height has been deprecated.



In [37]:
des = np.load('../subm/densenet201_98_0.05239213012534667_0.030665695160758077_0.9842336166712367_0.8787061994609164_tta_arithmetic.npy')
dpn = np.load('../subm/dpn131_68_0.22852461410608763_0.04059238999003643_0.9812174389909515_0.9376731301939059_tta_arithmetic.npy')
ir = np.load('../subm/inceptionresnetv2_115_0.2800604541126328_0.022912003500223682_0.9757334795722512_0.9158686730506156_tta_arithmetic.npy')
res = np.load('../subm/resnet152_154_0.21108618408131102_0.03966159357182812_0.972717301891966_0.9236016371077762_tta_arithmetic.npy')
nxt = np.load('../subm/resnext101_64x4d_106_0.05270318477823023_0.021929375704770025_0.9839594187003016_0.9042253521126761_tta_arithmetic.npy')

In [23]:
log_des,log_dpn,log_ir,log_res,log_nxt = softmax(des),softmax(dpn),softmax(ir),softmax(res),softmax(nxt)

In [29]:
log_des[5]

array([  1.92419052e-13,   7.40746701e-19,   3.15109574e-23,
         4.52958187e-03,   9.95470405e-01,   2.58423734e-18,
         1.64281037e-18,   3.16266585e-17,   8.49806292e-16,
         7.99755859e-21], dtype=float32)

In [30]:
log_dpn[5]

array([  1.34047355e-21,   1.23170697e-22,   7.68389127e-25,
         1.00000000e+00,   3.24597451e-08,   6.84945717e-19,
         5.68170314e-23,   1.54625999e-18,   9.16310461e-19,
         1.09567948e-20], dtype=float32)

In [31]:
log_ir[5]

array([  5.34720402e-12,   5.18682052e-20,   1.02097877e-21,
         9.98099744e-01,   1.90022716e-03,   1.87846793e-15,
         5.02106205e-22,   4.87080765e-10,   4.13611880e-14,
         1.50600301e-16], dtype=float32)

In [32]:
log_res[5]

array([  5.11058698e-13,   1.21207311e-13,   2.21446391e-17,
         3.59865755e-01,   6.40134215e-01,   1.64679631e-13,
         1.69486168e-15,   7.67475083e-10,   8.62947055e-16,
         8.66028102e-14], dtype=float32)

In [33]:
log_nxt[5]

array([  8.49972406e-15,   1.73472627e-23,   6.45825711e-24,
         1.00000000e+00,   1.77839687e-11,   1.71831545e-21,
         1.20825753e-21,   1.47330942e-17,   6.42014455e-21,
         1.35937723e-21], dtype=float32)

In [39]:
#mean = (log_des+log_dpn+log_ir+log_res+log_nxt)/5
mean = (des+res+nxt)/3

In [40]:
ids = glob.glob(join(TEST_FOLDER, '*.tif'))
ids.sort()
with conditional(True, open('submision_log_3mean.csv', 'w')) as csvfile:
    csv_writer = csv.writer(csvfile, delimiter=',',quotechar='|', quoting=csv.QUOTE_MINIMAL)
    csv_writer.writerow(['fname', 'camera'])
    for i, idx in enumerate(tqdm(ids)):
        prediction_class_idx = np.argmax(mean[i])
        csv_writer.writerow([idx.split('/')[-1], CLASSES[prediction_class_idx]])
        

100%|██████████| 2640/2640 [00:00<00:00, 160722.30it/s]


In [17]:
rets = pd.DataFrame()
rets['des'] = pd.read_csv('../subm/submission_densenet201_98_0.05239213012534667_0.030665695160758077_0.9842336166712367_0.8787061994609164_tta_arithmetic.csv')['camera']
rets['dpn'] = pd.read_csv('../subm/submission_dpn131_68_0.22852461410608763_0.04059238999003643_0.9812174389909515_0.9376731301939059_tta_arithmetic.csv')['camera']
rets['ir'] = pd.read_csv('../subm/submission_inceptionresnetv2_115_0.2800604541126328_0.022912003500223682_0.9757334795722512_0.9158686730506156_tta_arithmetic.csv')['camera']
rets['res']  = pd.read_csv('../subm/submission_resnet152_154_0.21108618408131102_0.03966159357182812_0.972717301891966_0.9236016371077762_tta_arithmetic.csv')['camera']
rets['nxt'] = pd.read_csv('../subm/submission_resnext101_64x4d_106_0.05270318477823023_0.021929375704770025_0.9839594187003016_0.9042253521126761_tta_arithmetic.csv')['camera']
rets['mean'] = pd.read_csv('submision_mean.csv')['camera']

In [18]:
rets.shape

(2640, 6)

In [19]:
rets

des                   dpn                    ir                   res                   nxt                  mean
0              LG-Nexus-5x           LG-Nexus-5x           LG-Nexus-5x           LG-Nexus-5x      Motorola-Nexus-6           LG-Nexus-5x
1                iPhone-4s             iPhone-4s             iPhone-4s             iPhone-4s             iPhone-4s             iPhone-4s
2                 iPhone-6              iPhone-6              iPhone-6              iPhone-6              iPhone-6              iPhone-6
3        Samsung-Galaxy-S4     Samsung-Galaxy-S4     Samsung-Galaxy-S4     Samsung-Galaxy-S4     Samsung-Galaxy-S4     Samsung-Galaxy-S4
4               Motorola-X            Motorola-X            Motorola-X            Motorola-X            Motorola-X            Motorola-X
5        Samsung-Galaxy-S4            Motorola-X            Motorola-X     Samsung-Galaxy-S4            Motorola-X            Motorola-X
6                 HTC-1-M7              HTC-1-M7              HTC-1-M7              HTC-1-M7              HTC-1-M7              HTC-1-M7
7                 HTC-1-M7              HTC-1-M7              HTC-1-M7              HTC-1-M7              HTC-1-M7              HTC-1-M7
8                iPhone-4s             iPhone-4s             iPhone-4s             iPhone-4s             iPhone-4s             iPhone-4s
9              LG-Nexus-5x  Samsung-Galaxy-Note3           LG-Nexus-5x  Samsung-Galaxy-Note3           LG-Nexus-5x           LG-Nexus-5x
10              Motorola-X            Motorola-X            Motorola-X            Motorola-X            Motorola-X            Motorola-X
11              Sony-NEX-7            Sony-NEX-7            Sony-NEX-7            Sony-NEX-7            Sony-NEX-7            Sony-NEX-7
12             LG-Nexus-5x           LG-Nexus-5x           LG-Nexus-5x           LG-Nexus-5x           LG-Nexus-5x           LG-Nexus-5x
13    Samsung-Galaxy-Note3  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3
14               iPhone-4s             iPhone-4s             iPhone-4s             iPhone-4s             iPhone-4s             iPhone-4s
15    Samsung-Galaxy-Note3  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3
16    Samsung-Galaxy-Note3  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3   Motorola-Droid-Maxx  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3
17                HTC-1-M7              HTC-1-M7              HTC-1-M7              HTC-1-M7              HTC-1-M7              HTC-1-M7
18              Sony-NEX-7            Sony-NEX-7            Sony-NEX-7            Sony-NEX-7            Sony-NEX-7            Sony-NEX-7
19             LG-Nexus-5x           LG-Nexus-5x     Samsung-Galaxy-S4  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3           LG-Nexus-5x
20               iPhone-4s             iPhone-4s             iPhone-4s             iPhone-4s             iPhone-4s             iPhone-4s
21    Samsung-Galaxy-Note3  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3
22                HTC-1-M7              HTC-1-M7              HTC-1-M7              HTC-1-M7              HTC-1-M7              HTC-1-M7
23                HTC-1-M7              HTC-1-M7              HTC-1-M7              HTC-1-M7              HTC-1-M7              HTC-1-M7
24                HTC-1-M7              HTC-1-M7              HTC-1-M7              HTC-1-M7              HTC-1-M7              HTC-1-M7
25              Sony-NEX-7            Sony-NEX-7            Sony-NEX-7            Sony-NEX-7            Sony-NEX-7            Sony-NEX-7
26    Samsung-Galaxy-Note3  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3  Samsung-Galaxy-Note3
27       Samsung-Galaxy-S4     Samsung-Galaxy-S4     Samsung-Galaxy-S4     Samsung-Galaxy-S4     Samsung-Galaxy-S4     Samsung-Galaxy-S4
28                iPhone-6              iPhone-6  

In [ ]:
5