In [266]:
import numpy as np
import pandas as pd
import scipy as sp
from sklearn.metrics import log_loss
from scipy.optimize import minimize

In [267]:
def get_minmax(df):
    a=np.where(np.sum((df.iloc[:,:7]>.5).astype(int),axis=1)>3,
                                    df['is_iceberg_max'],
                                    df['is_iceberg_min'])

    return a

def get_max(df):
    a=df.iloc[:,:7].max(axis=1)
    return a

def get_mean(df):
    a=df.iloc[:,:7].mean(axis=1)
    return a


def get_median(df):
    a=df.iloc[:,:7].median(axis=1)
    return a

def mae_func(weights,Y_values,predictions):
    ''' scipy minimize will pass the weights as a numpy array '''
    final_prediction = 0
    for weight, prediction in zip(weights, predictions):
            final_prediction += weight*prediction
    #print(final_prediction.shape)
    #print(prediction.shape)
    #print(Y_values.shape)
    return log_loss(Y_values, final_prediction)

def get_mini(df):
    predictions=[]
    Y_values = df['is_iceberg'].values
    #print(Y_values.shape)
    lls = []
    wghts = []
    for i in range(7):
        predictions.append(np.array(df.iloc[:,i]))

    for i in range(100):
        starting_values = np.random.uniform(size=7)
        cons = ({'type':'eq','fun':lambda w: 1-sum(w)})
        bounds = [(0,1)]*len(predictions)

        res = minimize(fun=mae_func, x0=starting_values,args=(Y_values, predictions), method='L-BFGS-B', bounds=bounds, options={'disp': False, 'maxiter': 100000})

        lls.append(res['fun'])
        wghts.append(res['x'])
    # Uncomment the next line if you want to see the weights and scores calculated in real time
    #    print('Weights: {weights}  Score: {score}'.format(weights=res['x'], score=res['fun']))

    bestSC = np.min(lls)
    bestWght = wghts[np.argmin(lls)]
    #print(bestSC)
    print(bestWght)
    a = 0.0*Y_values
    for weight, prediction in zip(bestWght, predictions):
        a += weight*prediction
    return a

In [268]:
def gen_type(df):
    hig = .8
    mid = .5
    low = .2

    if df.lr9>.8 and df.is_iceberg<.5:
        return 1
    if df.lr9<.2 and df.is_iceberg>.5:
        return 1
    return 0

In [269]:
def gen_test(df,m,n):
    df['new_pred'] = df['lr9']
    #a = df#[df.type==3]
    a = df[df[m]>=n]
    index = a.index
    print(a.shape)
    print('orig logloss is: ',log_loss(df['is_iceberg'], df['lr9']))
    pred = get_minmax(a)
    df.loc[index,'new_pred'] = pred.clip(0.001,0.999)
    print('minmax logloss is: ',log_loss(df['is_iceberg'],df['new_pred']))
    df['new_pred'] = df['lr9']
    #print('minmax logloss is: ',log_loss(df['is_iceberg'],df['new_pred']))

    pred = get_mean(a)
    df.loc[index,'new_pred'] = pred.clip(0.001,0.999)
    print('mean logloss is: ',log_loss(df['is_iceberg'],df['new_pred']))
    df['new_pred'] = df['lr9']
    #print('mean logloss is: ',log_loss(df['is_iceberg'],df['new_pred']))

    pred = get_median(a)
    df.loc[index,'new_pred'] = pred.clip(0.001,0.999)
    print('median logloss is: ',log_loss(df['is_iceberg'],df['new_pred']))
    df['new_pred'] = df['lr9']
    #print('median logloss is: ',log_loss(df['is_iceberg'],df['new_pred']))

    pred = get_mini(a)
    df.loc[index,'new_pred'] = pred.clip(0.001,0.999)
    print('mini logloss is: ',log_loss(df['is_iceberg'],df['new_pred']))
    df['new_pred'] = df['lr9']
    #print('mini logloss is: ',log_loss(df['is_iceberg'],df['new_pred']))


In [270]:
train = pd.read_csv('myvalid.csv')
test = pd.read_csv('mytest.csv')
train['is_iceberg_max'] = train.iloc[:, :7].max(axis=1)
train['is_iceberg_min'] = train.iloc[:, :7].min(axis=1)
train['is_iceberg_mean'] = train.iloc[:, :7].mean(axis=1)
train['is_iceberg_median'] = train.iloc[:, :7].median(axis=1)
train['is_iceberg_std'] = train.iloc[:, :7].std(axis=1)
test['is_iceberg_max'] = test.iloc[:, :7].max(axis=1)
test['is_iceberg_min'] = test.iloc[:, :7].min(axis=1)
test['is_iceberg_mean'] = test.iloc[:, :7].mean(axis=1)
test['is_iceberg_median'] = test.iloc[:, :7].median(axis=1)
test['is_iceberg_std'] = test.iloc[:, :7].std(axis=1)

train['type'] = train.apply(gen_type,1)
#test['type'] = test.apply(gen_type,1)

In [271]:
gen_test(train,'type',.9)

(34, 16)
orig logloss is:  0.125017134156
minmax logloss is:  0.140457222874
mean logloss is:  0.102154960145
median logloss is:  0.109711374969
[ 1.  1.  1.  1.  1.  1.  1.]
mini logloss is:  0.147782394677


In [272]:
train[train.type==1]

orig1+TLres50  trans1+TLvgg16+Adam  normf1+TLvgg16    mix+lr   mix+lgb  \
26         0.163231             0.131698        0.054178  0.980769  0.402647   
161        0.992831             0.964832        0.971465  0.998016  0.984880   
178        0.155006             0.049144        0.122662  0.953943  0.229853   
276        0.668055             0.584428        0.431836  0.101356  0.114832   
292        0.395070             0.110221        0.538535  0.038943  0.122276   
308        0.037274             0.036769        0.020798  0.032937  0.030173   
333        0.937305             0.925763        0.921871  0.770765  0.678706   
350        0.978347             0.934119        0.903692  0.734713  0.917766   
364        0.928160             0.829317        0.961569  0.693024  0.932323   
370        0.337595             0.636648        0.629657  0.169332  0.113514   
462        0.088885             0.133706        0.624119  0.179305  0.377087   
562        0.835171             0.844869        0.638103  0.502649  0.408982   
651        0.375417             0.437338        0.722559  0.522890  0.938852   
661        0.901814             0.702368        0.348486  0.756717  0.789169   
684        0.838909             0.896258        0.949342  0.719365  0.831304   
743        0.316417             0.446939        0.302408  0.251646  0.502145   
753        0.057107             0.006504        0.021739  0.003001  0.054998   
791        0.961608             0.973652        0.781880  0.914637  0.985917   
795        0.793969             0.978606        0.969772  0.713314  0.902842   
861        0.283816             0.309681        0.587182  0.000031  0.083383   
865        0.969784             0.973139        0.728381  0.801494  0.567602   
892        0.071795             0.001347        0.003922  0.038500  0.031590   
905        0.998904             0.909958        0.951513  0.988660  0.956048   
986        0.784503             0.821434        0.926473  0.588953  0.915309   
1118       0.164665             0.149593        0.145571  0.265491  0.045455   
1175       0.927356             0.759116        0.592040  0.644926  0.897102   
1185       0.651111             0.829647        0.791946  0.952865  0.637458   
1190       0.598678             0.229379        0.492557  0.032080  0.222924   
1224       0.031633             0.136836        0.051296  0.137906  0.047892   
1230       0.628549             0.490115        0.936321  0.731954  0.792447   
1329       0.605850             0.757241        0.985781  0.389568  0.688807   
1387       0.983568             0.929661        0.875068  0.902247  0.695866   
1417       0.751119             0.779053        0.786451  0.974742  0.958120   
1473       0.392970             0.165756        0.504006  0.608240  0.515284   

       mix+svm       lr9        id  is_iceberg  is_iceberg_max  \
26    0.777715  0.103521  958d42a8           1        0.980769   
161   0.997456  0.988721  2f881d78           0        0.998016   
178   0.096160  0.037888  a9ab128c           1        0.953943   
276   0.317042  0.180001  e0323d3d           1        0.668055   
292   0.033113  0.042504  a996191d           1        0.538535   
308   0.015020  0.008056  87319e1c           1        0.037274   
333   0.644751  0.948894  74c92938           0        0.948894   
350   0.585872  0.965975  1303a495           0        0.978347   
364   0.752311  0.965776  5a501d33           0        0.965776   
370   0.095298  0.198777  2d348f42           1        0.636648   
462   0.169005  0.075585  3c98959e           1        0.624119   
562   0.897141  0.834270  55a724b1           0        0.897141   
651   0.868659  0.826154  f613255d           0        0.938852   
661   0.725438  0.845694  786ee92d           0        0.901814   
684   0.802169  0.967339  fd1f0c9b           0        0.967339   
743   0.478173  0.197937  b7ca0494           1        0.502145   
753   0.005626  0.005647  3b431e27           1        0.057107   
791   0.839045  0

In [318]:
train['lrdis'] = np.abs(train['lr9']-train['is_iceberg_std'])
train['dis'] = np.abs(train['is_iceberg_max']-train['is_iceberg_min'])
train['lrstd'] = np.sqrt((np.square(train['orig1+TLres50']-train['lr9'])+
                        np.square(train['trans1+TLvgg16+Adam']-train['lr9'])+
                        np.square(train['normf1+TLvgg16']-train['lr9'])+
                        np.square(train['mix+lr']-train['lr9'])+
                        np.square(train['mix+lgb']-train['lr9'])+
                        np.square(train['mix+svm']-train['lr9']))/6)
y = train.loc[:,'type']
y.drop([161,308,753,892,905],inplace=True)
X = train.loc[:,['lrstd','is_iceberg_std','is_iceberg_mean','lr9']]#
X.drop([161,308,753,892,905],inplace=True)
from sklearn.preprocessing import MinMaxScaler
scaling = MinMaxScaler(feature_range=(-1,1)).fit(X)
X = pd.DataFrame(scaling.transform(X),columns=X.columns)

In [319]:
log = 'knn'
if log == 'lr':
    from sklearn.linear_model import LogisticRegression
    C_regu = 1
    lr_model = LogisticRegression(penalty='l1',C=C_regu)
    log_model = lr_model
if log == 'nb':
    from sklearn.naive_bayes import GaussianNB
    lr_model = GaussianNB()
    log_model = lr_model
if log == 'knn':
    from sklearn.neighbors import KNeighborsClassifier
    lr_model = KNeighborsClassifier(n_neighbors=25, weights='distance')
    log_model = lr_model
if log == 'lda':
    from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
    lr_model = LinearDiscriminantAnalysis()
    log_model = lr_model
if log == 'qda':
    from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
    lr_model = QuadraticDiscriminantAnalysis()
    log_model = lr_model
if log == 'nc':
    from sklearn.neighbors.nearest_centroid import NearestCentroid
    lr_model = NearestCentroid()
    log_model = lr_model

In [321]:
from sklearn.model_selection import KFold
K = 1599
kf = KFold(n_splits=K, random_state = 1108, shuffle = False)
a = 0
b = 0
c = []
d = []
for i, (train_index, test_index) in enumerate(kf.split(X)):
    y_train, y_valid = y.iloc[train_index].copy(), y.iloc[test_index]
    X_train, X_valid = X.iloc[train_index,:].copy(), X.iloc[test_index,:].copy()
    model = log_model
    model.fit(X_train,y_train)
    tmp=model.score(X_valid,y_valid)
    a+=tmp
    tmp = model.predict(X_valid)[0]
    b+=tmp
    
    tmp = model.predict_proba(X_valid)[0,1]
    #print(tmp)
    c.append(tmp)
    #print(y_valid.values)
    d.append(y_valid.values[0])
print(a)
print(b)
#print(d,c)
print(log_loss(y.values,d))
print(log_loss(y.values,c))
print(log_loss(d,c))
a

1572.0
2
9.99200722163e-16
0.124621701456
0.124621701456


1572.0

In [322]:
train['new_type'] = c

ValueError: Length of values does not match length of index

In [310]:
train[train.new_type>=.1].shape

(143, 20)

In [340]:
gen_test(train,'dis',.91)

(6, 20)
orig logloss is:  0.125017134156
minmax logloss is:  0.128905111591
mean logloss is:  0.122795802362
median logloss is:  0.124017380665
[ 0.          0.          0.          0.76558854  0.          0.          0.        ]
mini logloss is:  0.121212121116


In [317]:
train[train.new_type>=.45]

orig1+TLres50  trans1+TLvgg16+Adam  normf1+TLvgg16    mix+lr   mix+lgb  \
21         0.084159             0.601634        0.789117  0.143754  0.871721   
198        0.119601             0.596353        0.817323  0.456248  0.709919   
229        0.751123             0.716590        0.705483  0.655559  0.901599   
325        0.502183             0.668711        0.743911  0.480930  0.833167   
378        0.474965             0.165493        0.260870  0.550372  0.285898   
538        0.640261             0.876056        0.673962  0.590024  0.903027   
545        0.542528             0.852167        0.871039  0.639971  0.798476   
550        0.195511             0.185765        0.452224  0.504511  0.247234   
710        0.557716             0.166456        0.272904  0.542138  0.439602   
808        0.679462             0.598211        0.907389  0.604448  0.954651   
994        0.617677             0.869099        0.634953  0.242846  0.892542   
1076       0.684420             0.654560        0.667490  0.644293  0.639411   
1307       0.483471             0.200814        0.187154  0.803315  0.232230   
1357       0.572577             0.788537        0.743255  0.420821  0.818673   

       mix+svm       lr9        id  is_iceberg  is_iceberg_max  \
21    0.664435  0.769775  112a6cfa           1        0.871721   
198   0.679267  0.781428  1c536d78           0        0.817323   
229   0.697929  0.900649  72da83eb           1        0.901599   
325   0.555934  0.812832  c0ce2db6           1        0.833167   
378   0.568161  0.116082  430f9c05           0        0.568161   
538   0.517185  0.901911  29ad22d1           1        0.903027   
545   0.612177  0.926169  b5168440           1        0.926169   
550   0.613155  0.107299  246a9cf9           0        0.613155   
710   0.296192  0.144492  49f4d394           0        0.557716   
808   0.713161  0.924682  1b059732           1        0.954651   
994   0.426061  0.828385  74725cf4           1        0.892542   
1076  0.826442  0.834699  fb1c466e           1        0.834699   
1307  0.623859  0.131556  89a339cf           0        0.803315   
1357  0.613659  0.856788  92aa3e8a           1        0.856788   

      is_iceberg_min  is_iceberg_mean  is_iceberg_median  is_iceberg_std  \
21          0.084159         0.560656           0.664435        0.317803   
198         0.119601         0.594306           0.679267        0.241435   
229         0.655559         0.761276           0.716590        0.099597   
325         0.480930         0.656810           0.668711        0.146169   
378         0.116082         0.345977           0.285898        0.184418   
538         0.517185         0.728918           0.673962        0.161706   
545         0.542528         0.748932           0.798476        0.148668   
550         0.107299         0.329386           0.247234        0.191878   
710         0.144492         0.345643           0.296192        0.169666   
808         0.598211         0.768858           0.713161        0.155583   
994         0.242846         0.644509           0.634953        0.243460   
1076        0.639411         0.707331           0.667490        0.085532   
1307        0.131556         0.380343           0.232230        0.258916   
1357        0.420821         0.687759           0.743255        0.157564   

      type  new_pred     lrdis       dis     lrstd  new_type  
21       0  0.769775  0.451972  0.787562  0.389895  0.603550  
198      0  0.781428  0.539993  0.697722  0.314867  0.556454  
229      0  0.900649  0.801052  0.246040  0.180504  0.547117  
325      0  0.812832  0.666663  0.352237  0.223082  0.526078  
378      0  0.116082  0.068336  0.452079  0.309306  0.786857  
538      0  0.901911  0.740205  0.385842  0.247110  0.689708  
545      0  0.926169  0.777501  0.383641  0.242385  0.798374  
550      0  0.107299  0.084579  0.505856  0.307181  0.666231  
710      0  0.144492  0.025174  0.413224  0.275666  0.532064  
808      0  0.924682  0.769099  0.356440  0

In [83]:
mytest = np.array([[0,1],[1,1],[2,1],[3,1],[4,1],[5,1],[6,1],[7,1],[8,1],[9,1]])
mykf = KFold(n_splits=10, random_state = 1108, shuffle = False)
for i, (train_index, test_index) in enumerate(mykf.split(mytest)):
    print(train_index,test_index)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


In [40]:
1571/1604

0.979426433915212

In [69]:
    model = log_model
    model.fit(X,y)
    model.score(X,y)

0.97880299251870329

In [342]:
train[train.dis>.89]


orig1+TLres50  trans1+TLvgg16+Adam  normf1+TLvgg16    mix+lr   mix+lgb  \
26         0.163231             0.131698        0.054178  0.980769  0.402647   
178        0.155006             0.049144        0.122662  0.953943  0.229853   
329        0.259603             0.555264        0.958281  0.047329  0.086697   
644        0.400437             0.395778        0.034612  0.877413  0.981761   
679        0.008681             0.131030        0.467136  0.978729  0.849243   
700        0.450949             0.920850        0.960072  0.289282  0.065857   
865        0.969784             0.973139        0.728381  0.801494  0.567602   
904        0.221260             0.114681        0.118583  0.957846  0.051696   
998        0.082144             0.000185        0.000327  0.902701  0.145994   
1062       0.977321             0.981095        0.507612  0.864349  0.084257   
1278       0.131056             0.313781        0.041303  0.624482  0.959475   

       mix+svm       lr9        id  is_iceberg  is_iceberg_max  \
26    0.777715  0.103521  958d42a8           1        0.980769   
178   0.096160  0.037888  a9ab128c           1        0.953943   
329   0.559568  0.431034  0d42919f           0        0.958281   
644   0.846545  0.554242  86ff8b5e           0        0.981761   
679   0.216368  0.201254  606412bc           1        0.978729   
700   0.408385  0.581704  e870fc10           1        0.960072   
865   0.081170  0.878411  dedf2035           0        0.973139   
904   0.637126  0.077182  5922e495           0        0.957846   
998   0.570641  0.034986  308fc1fe           0        0.902701   
1062  0.234959  0.611265  be24e1d3           1        0.981095   
1278  0.386708  0.242370  49f9ebbf           0        0.959475   

      is_iceberg_min  is_iceberg_mean  is_iceberg_median  is_iceberg_std  \
26          0.054178         0.373394           0.163231        0.367548   
178         0.037888         0.234951           0.122662        0.323676   
329         0.047329         0.413968           0.431034        0.317041   
644         0.034612         0.584398           0.554242        0.337903   
679         0.008681         0.407492           0.216368        0.374067   
700         0.065857         0.525300           0.450949        0.325233   
865         0.081170         0.714283           0.801494        0.313416   
904         0.051696         0.311196           0.118583        0.348878   
998         0.000185         0.248140           0.082144        0.350897   
1062        0.084257         0.608694           0.611265        0.357040   
1278        0.041303         0.385596           0.313781        0.315014   

      type  new_pred     lrdis       dis     lrstd  new_type  
26       1  0.103521  0.264027  0.926591  0.469108  0.282667  
178      1  0.037888  0.285788  0.916055  0.387391  0.054569  
329      0  0.431034  0.113993  0.910952  0.317577  0.004307  
644      0  0.554242  0.216339  0.947149  0.339469  0.003547  
679      0  0.201254  0.172813  0.970048  0.435372  0.071163  
700      0  0.581704  0.256471  0.894215  0.330890  0.007536  
865      1  0.878411  0.564995  0.891969  0.360079  0.112931  
904      0  0.077182  0.271696  0.906150  0.430820  0.201165  
998      0  0.034986  0.315911  0.902516  0.419685  0.106494  
1062     0  0.611265  0.254225  0.896838  0.357050  0.003970  
1278     0  0.242370  0.072644  0.918172  0.350951  0.017918